### ISSUE TITLE
Transforms in MixedSingleTaskGP

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#1054]
Hi, 

I saw the implemention of a `MixedSingleTaskGP` with the combination of a continuous and a categorical kernel to overcome problems with one hot encodings and I really like it.

I was just wondering if input and output transforms are working with this kind of GP as they are commented out in the docstring and marked with "todo" in the `__init__` method https://github.com/pytorch/botorch/blob/51b3202dcccf2a1356649c512df4caf77cd91c33/botorch/models/gp_regression_mixed.py#L56). Nevertheless, one can provide transforms and they are also parsed to the constructor of the "SingleTaskGP" class form which `MixedSingleTaskGP`  is inherited from. 

So my question is: Do you expect that the  `MixedSingleTaskGP` is working with transforms? 

Best,

Johannes

**Comment by jduerholt** [comment]
I just saw that errors are raised if it is used in combination with input/output transforms. In the moment, I only see a possible problem with input transforms. Assume, you have a categorical variable with three possible levels, represented via integers 1, 2, 3. Applying a `Normalize` transform would lead to floating point numbers which could cause numeric problems in the categorical kernel when the equality of `X` values is checked. 

If this is the reason, one should allow only input transforms which ignore the categorical columns in the transform.

Would this be a solution?

**Comment by Balandat** [comment]
Thanks for flagging this.

I believe the main reason here is that we were moving fast at the time so we didn't have a lot of time to think about this carefully - thanks for doing that for us :). 

I agree that it does seem that there shouldn't really be any issues with outcome transforms.

As to input transforms, yes, restricting the input transforms to those that do not act on the categorical features seems like a good solution. We'd probably want to add some property to the `InputTransform` API (e.g. `active_colums`) so that we can access that information universally from the transforms without having to special case - then we could just error in the constructor of `MixedSingleTaskGP` if the active columns of the `InputTransform` include one of the categorical ones. How does that sound?

**Comment by jduerholt** [comment]
Hi,

I like the idea, in this PR https://github.com/pytorch/botorch/pull/1053#discussion_r780224003 we have already started to discuss how to establish a common `InputTransform` API for `normalize` and `standardize`, including the `indices` keyword which is in principle the same as `active_columns` (maybe we should rename it to make it consistense with gpytorch's Kernel API)

Would this already be sufficient or would you add a property to the base `InputTransform` API?

Best,

Johannes

**Comment by saitcakmak** [comment]
I also think that it is a good idea to keep the names separate. Adding a property to `InputTransform` sounds like a good way to go. 

Regarding implementation, I don't think `MixedSingleTaskGP` should force the use of `indices` (e.g., by automatically ignoring the deterministic indices)  but rather keep it optional, enabled via an input to the constructor. I'd like to be able to use transforms that do not support `indices`. E.g., for `InputPerturbation`, I could specify the perturbations as `0` for the  ones I don't want to perturb and use it even though it does not support `indices`.

> Assume, you have a categorical variable with three possible levels, represented via integers 1, 2, 3. Applying a Normalize transform would lead to floating point numbers which could cause numeric problems in the categorical kernel when the equality of X values is checked.

This does not happen, right? I'd assume that the equality should still hold after applying a deterministic transformation. If it does happen, I wonder if it would be wise to change the `equal` check (which I assume is being used) in the kernel with an `allclose` to allow for numerical imprecision.

**Comment by jduerholt** [comment]
Hi @saitcakmak , thanks for joining the discussion. You are correct, enforcing `indices` could lead to problems, also in the context of chained transforms. 

Regarding your comment, regarding mine on the normalization of categoricals. I am not sure if it happens, it was the only reason that I could imagine for not allowing input transforms for the mixed GP. If this is not a problem than one could allow them, or?

Maybe, we should test it ;)

Best,

Johannes

**Comment by Balandat** [comment]
> Maybe, we should test it ;)

Now here's an idea. Though the suggestion to test generally signals a lack of delusion about one's own infallibility, so why trust you on this? 

Re the categorical variables for the `MixedSingleTaskGP` - it's *probably* ok, but I am a bit worried about weird edge cases where due to some fitting issues with the transform we suddenly end up in a case where due to numerical precision issues the equality comparison breaks down. If there isn't a real reason to support this I would probably err on the side of caution for now and disallow transformation of categorical columns. Are there any downsides to doing this other than having to write slightly more verbose code?

**Comment by jduerholt** [comment]
You are right, testing against the edge cases could be difficult. I am totally fine with your proposed solution disallowing transformation of categorical columns. One other thing I would add to the MixedSingleTaskGP is to give the possibility to pass further arguments to the `cont_kernel_factory` via a `kernel_kwargs` argument given to the constructor which is then always passed to the `cont_kernel_factory`.

What do you think?

I'll try to setup a basic for both things during the course of the week, if this is fine for you.

Best,

Johannes

**Comment by saitcakmak** [comment]
I believe this was fixed by #1060. Thanks @jduerholt !
