### ISSUE TITLE
Slow acquisition function optimization

### ISSUE THREAD

**Issue by npielawski** [pytorch/botorch#1222]
I am working on a Multi-Fidelity Bayesian Optimization task, where each fidelity costs about 13% of the previous higher fidelity. The true function takes between 1-10 seconds to compute and I am using 4 fidelities.

My issue is that the optimization of the acquisition function takes so much time. With default parameters, it takes between 30-60 seconds to predict the next point. I am searching the Multi-Fidelity GIBBON acquisition function's maximum using optimize_acqf_mixed on a 3D space. I double checked to make sure it was L-BFGS-B that was being run.

Here are things I tried:
- Different set of parameters: mixed results but not much improvement
- Multithreading: it's seems that the optimization of scipy is locking the threads (so they are idling)
- Multiprocessing: Failed to pickle the acquisition function
- [Parallel version of scipy optimize](https://github.com/florafauna/optimParallel-python): Failed to pickle the acquisition function
- Torch version of L-BFGS-B: Only L-BFGS exists, the bounded version is on the todo list.

Is there anything that can be done to speed up the search?

## System Info
- BoTorch Version 0.6.4
- GPyTorch Version 1.6.0
- PyTorch Version 1.9.1
- Computer OS Mac OS Monterey v12.3.1

**Comment by npielawski** [comment]
Setting "sample_around_best" to True in `optimize_acqf_mixed` helped and reduced the time by up to two times. I will test on other computers on Monday.

Maybe there is a way to parallelize the loop over the fidelities? Or maybe use the resulting points from the top fidelity and use them as starting points for the lower fidelities? Granted, that would bias the search but would give a `n` fold speed increase for `n` fidelities.

**Comment by Balandat** [comment]
So one general comment is that if your function only takes seconds to compute then using a sophisticated multi-fidelity Bayesian Optimization approach might not be the best thing to do. Optimizing the acquisition function well is quite expensive for such models, and while you can bring that runtime down some, it will still be comparable (and likely even longer in the large data regime) in the runtime as the actual function evaluation. 

We typically use these approaches when an individual evaluation takes on the order of tens of minutes up to multiple day, in which case that overhead is negligible.

To answer your question more specifically: BoTorch/GPyTorch use a lot of automatic parallelization (via MKL threading or GPU parallelism) under the hood. Therefore it is often not very beneficial to parallelize the optimization, unless that is done across machines. 

I think in your particular case, if you do care about situations in which each evaluation takes a few seconds, it makes more sense to look at cheaper optimization approaches - either some cheaper BO alternatives (such as thompson sampling instead of optimizing the acquisition function) or even beyond that (e.g. evolutionary methods, which will also scale a lot more gracefully with the number of observations).

**Comment by npielawski** [comment]
Alright, thanks for your detailed answer!

I tried Thompson Sampling, but I got greedy with all the nice acquisition functions of Botorch. :)
I will look into evolutionary methods.
