### ISSUE TITLE
[Question] How to add constrains to output of optimize_acqf_discrete_local_search?

### ISSUE THREAD

**Issue by RossXli** [pytorch/botorch#1252]
Hello, everyone. I am material developer and a big fan of BoTorch.
When I implemented `optimize_acqf_discrete_local_search()` to get new candidate, which is a composition ratio of some raw materials in form of tensor[x1,x2,x3,x4,x5] , I want to add constrains which could be described as  "x1+x2+x3+x4+x5 =1" to output tensor. Is it possible and how?
I guess args `constraints` may work, but I have no idea on how to specify it.
Thanks.

**Comment by Balandat** [comment]
Currently `optimize_acqf_discrete_local_search` only supports inequality constraints. 

Basically the way it works is via rejection sampling - we keep generating choices from the marginal choices in each dimension and filtering out infeasible choices. We could add a `equality_constraints` argument that applies in the same way, but for this to work reasonably well in the same fashion the cardinality of the individual choices would have to be small enough for this constraint to be satisfied reasonably often enough when sampling the combinations (otherwise we'd just keep rejecting suggestions in perpetuity). 

A better alternative may be to sample incrementally, i.e. sample `x1` from the choices subject to the constraint that `x1 <= 1`, then sample `x2` s.t. `x2 <= 1 - x1`, etc. (we'd have to cycle the order of the `xi` around here I guess). 

Taking a step back, are your choices actually discrete in this setting? It seems that a composition ratio should be continuous in which case we can apply a simplex constraint to the generation in `optimize_acqf`. I know that in practice you may want to choose discrete values (e.g. to simplify lab work), but as long as the discretization isn't super coarse it shouldn't be too bad to work in the continuous space and then round for the actual implementation. 

cc @dme65

**Comment by RossXli** [comment]
@Balandat 
Very appreciate for you kind explanation and suggestions.
Great work for you to develop BoTorch, which is of great help to us to implement BO in material development.
