### ISSUE TITLE
Broken gpytorch dependency

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#1609]
## Issue description

From my understanding the current dependency from the botorch main branch to gpytorch is broken, as version 1.9.0 is hardcoded in the `requirements.txt`.
https://github.com/pytorch/botorch/blob/1addd3a72facf739b2bc864de9c9863e817e66c1/requirements.txt#L5

But for installing botorch successfully with pip from git, the latest master version of gpytorch is need. Else botorch crashes as it cannot import `dist` from `gpytorch.kernels.kernel`.

I think one has to resolve the pinned version of gpytorch in the `requirements.txt`

**Comment by esantorella** [comment]
Yes, this is the same issue as #1605 . If you want to install from the latest commit of BoTorch on GitHub, rather than the stable PyPi / Conda release of BoTorch 0.8.0, you'll need to force installation of the latest commit of GPyTorch as described [here](https://github.com/pytorch/botorch#option-2-installing-from-latest-main-branch).

**Comment by jduerholt** [comment]
Thx, for the hint and sorry for not reading the other issue ;)
