### ISSUE TITLE
[Bug] How to obtain a better predictive mean

### ISSUE THREAD

**Issue by Display-ST** [pytorch/botorch#1911]
# 🐛 Bug

I'm not sure if it's a bug or not; sometimes I cannot get a predictive mean to fit well. Is there anything I can do to obtain a better predictive mean?

## To reproduce

It can be reproduced in the following notebook.
https://gist.github.com/Display-ST/df9f794e857bf445451123fa55d3a4d1

## Expected Behavior

I think BoTorch should be able to output an accurate predictive mean similar to scikit-learn.

## System information

- BoTorch: 0.8.5
- GPyTorch: 1.10
- PyTorch: 2.0.1
- Python: 3.10.6
- OS: Windows 10

**Comment by Balandat** [comment]
Your good sklearn fit is a mirage - the sklearn model completely overfits the data. 

If you evaluate the two models on a holdout set things look like this: 

![overfit](https://github.com/pytorch/botorch/assets/1605878/022f9d45-d09e-4b2b-b218-a6fdcb56776f)

Repro: [botoch_issue_1911.ipynb.txt](https://github.com/pytorch/botorch/files/11913036/botoch_issue_1911.ipynb.txt)


Aside:
In BoTorch you'll want to call `model.posterior(test_X)` instead of `likelihood(model(test_X))`, that's the standard interface that works consistently across model types and applies things like input/output transforms properly.

**Comment by Balandat** [comment]
I am not sure why sklearn fails this badly here, but I think it's b/c by default the GP regressor does not infer an observation noise level (hence the perfect in-sample predictions). You will likely have to use a `WhiteKernel` with whatever kernel you specify.

**Comment by Display-ST** [comment]
@Balandat Thank you for your quick response. 
It is true that overfitting of the model has occurred. On the other hand, in this issue I am rather motivated to overfit.  When I want to make the predictive mean of BoTorch model overfit the training data, how should I adjust?

**Comment by Display-ST** [comment]
>I think it's b/c by default the GP regressor does not infer an observation noise level (hence the perfect in-sample predictions). 

Sorry, I missed the following Issue. Since your comment helped me to realize this, the problem I had was solved. Thank you so much!!
https://github.com/cornellius-gp/gpytorch/issues/1196
