### ISSUE TITLE
How many outcome constraints can we set?

### ISSUE THREAD

**Issue by cyrilmyself** [pytorch/botorch#2215]
In my case, i need to set 3 obejcts and 6 outcome constraints; If i set as above, what will happen?

**Comment by sdaulton** [comment]
That should not be a problem. Please let us know if you encounter issues

**Comment by cyrilmyself** [comment]
@sdaulton thank you for your replying. 
What is the max number of outcome constraints can we set in practice？
And how many outcome constraints do you advice？

**Comment by sdaulton** [comment]
There isn't a limit per say, since typically each constraint is modeled with an independent GP. That said model fitting and candidate generation will be slower as more constraints are added---since there are more GPs being evaluated. Moreover, the optimization problem may become quite a bit harder if the feasible region becomes smaller.

**Comment by cyrilmyself** [comment]
@sdaulton thank you very much，it helps me a lot
