### ISSUE TITLE
Unexpected behavior setting kernel priors

### ISSUE THREAD

**Issue by ruhanaazam** [pytorch/botorch#2307]
Hi, I'm interested in setting better priors on my SingleTaskGP's kernel. I am unsure if I am setting the priors correctly. Below are two ways I have tried to set the kernel priors. I expect both to behave the same but when I fit my GP, I find that `cov_module1` works significantly better than `covar_module2`. Is there a reason for this behavior? 

```
lengthscale_prior = gpytorch.priors.GammaPrior(3.0, 6.0)
outputscale_prior = gpytorch.priors.GammaPrior(2.0, 0.15)

covar_module1 = ScaleKernel(
    MaternKernel(
        nu=nu,
        ard_num_dims=2,
        lengthscale_prior=lengthscale_prior,
    ),
    outputscale_prior=outputscale_prior,
)

covar_module2 = ScaleKernel(
    MaternKernel(
        nu=nu,
        ard_num_dims=2,
    ),
)
covar_module2.base_kernel.lengthscale_prior = lengthscale_prior
covar_module2.outputscale_prior = outputscale_prior
```

## Expected Behavior
`cov_module1` and `cov_module2` to perform similarly when they are used to fit a `SingleTaskGP`.

## System information

**Please complete the following information:**
Botorch: 0.8.3
GPyTorch: 1.10
Pytorch: 2.0.1
Ubuntu 20.04
Python: 3.10

**Comment by saitcakmak** [comment]
Hi @ruhanaazam. This question seems more fitting for [GPyTorch](https://github.com/cornellius-gp/gpytorch/issues) but I'll still try to answer it here. I recommend following up with an issue on GPyTorch repo for questions related to internals of GPyTorch modules.

If you check the source code for `Kernel`, you'll see that it uses `self.register_prior(...)` rather than `self.lengthscale_prior = ...` to set the prior. I believe this is required for the prior to be treated as a prior. The prior you set for `cov_module2` is likely being ignored here. See https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/kernels/kernel.py#L205-L207
