### ISSUE TITLE
Can MultiTaskGP be trained with batch data?

### ISSUE THREAD

**Issue by ybwang75** [pytorch/botorch#2369]
Hi, 
I hope to be able to use Gaussian processes in more complex projects, which are written using the pytorch, that is, with dataloader.

But I can't find any tutorials or examples about this. Most examples use a train_x and train_y to train a multitaskGP. 
Even if there are any, all I see are defining a multitaskGP for each batch of data. 

I want to know if there are any examples of Botorch that can be generalized. Can anyone tell me?

**Comment by saitcakmak** [comment]
Hi @ybwang75. By "trained with batch data", are you referring to mini-batch training, where you have a large dataset that you want to train the model on while evaluating it on a small subset at any given time? Out of the box `MultiTaskGP` will not support that. Most GP models in BoTorch, including `MultiTaskGP`, are exact GP models. We do have limited support for approximate GP models & mini-batch training for these models, though I am an expert on these. 
- The single-task approximate GP class: https://github.com/pytorch/botorch/blob/main/botorch/models/approximate_gp.py#L284
- A model fitting utility that, I believe, supports mini-batch training using dataloader: https://github.com/pytorch/botorch/blob/main/botorch/fit.py#L249  Unfortunately, we don't have much documentation on this one.
You may also find GPyTorch documentation useful for approximate models: https://docs.gpytorch.ai/en/stable/examples/04_Variational_and_Approximate_GPs/index.html

**Comment by ybwang75** [comment]
Thank you for your answer. Actually, what I want to ask is whether there is an example of DeepGP implemented in Botorch like gpytorch?

**Comment by saitcakmak** [comment]
We don't have an implementation of DeepGP. The BoTorch `Model` API has rather simple expectations, mainly that the model has a `posterior` method that produces a `Posterior` object that produces samples of expected shape. Since the `DeepGP` is a GPyTorch model that produces a `MultivariateNormal`, the posterior implementation would just need to wrap this in a `GPyTorchPosterior`.

- `GPyTorchPosterior`: https://github.com/pytorch/botorch/blob/main/botorch/posteriors/gpytorch.py#L35
- The base `Model` class: https://github.com/pytorch/botorch/blob/main/botorch/models/model.py#L57
- An example `posterior` implementation: https://github.com/pytorch/botorch/blob/main/botorch/models/gpytorch.py#L157

**Comment by Balandat** [comment]
> We don't have an implementation of DeepGP.

We have an old implementation sitting around that we haven't open-sourced. I have no idea how well that works, but I'd be happy to put out a PR to show how that looks like if that would be helpful.
