### ISSUE TITLE
[Bug] cholesky_cuda: U(1,1) error with certain types of Data on fit_gpytorch_model

### ISSUE THREAD

**Issue by Tenoke** [pytorch/botorch#237]
# 🐛 Bug

When using `fit_gpytorch_model` on certain types of data, I consistently get a `RuntimeError: cholesky_cuda: U(1,1) is zero, singular U.` error. This issue has been partially fixed, brought back and is currently fully present again.

## To reproduce

[Working Colab Example](https://colab.research.google.com/drive/1Lm2fYQ_5Owe88zP_yqf_HCEvf2LpqqPZ)

** Stack trace/error message **
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-7a985b2d2e2b> in <module>()
     53   mll = ExactMarginalLogLikelihood(model.likelihood, model,)
     54 
---> 55   fit_gpytorch_model(mll, optimizer=fit_gpytorch_torch)
     56   acq_function = UpperConfidenceBound(model, beta=0.1, maximize=False)
     57   candidates = joint_optimize(

10 frames
/usr/local/lib/python3.6/dist-packages/gpytorch/utils/cholesky.py in psd_safe_cholesky(A, upper, out, jitter)
     19     """
     20     try:
---> 21         L = torch.cholesky(A, upper=upper, out=out)
     22         # TODO: Remove once fixed in pytorch (#16780)
     23         if A.dim() > 2 and A.is_cuda:

RuntimeError: cholesky_cuda: U(1,1) is zero, singular U.
```

## Expected Behavior

For `fit_gpytorch_model` to successfully fit the model.

## System information

**Please complete the following information:**
Master versions of botorch and gpytorch on Google Colab.

**Comment by Balandat** [comment]
So there are two things here:

1. The numerical values of your training data are insane, this is going to mess up pretty much everything. Make sure this is computed correctly / standardized appropriately.
![Screen Shot 2019-08-13 at 9 08 03 AM](https://user-images.githubusercontent.com/1605878/62957649-12434800-bdaa-11e9-8d33-7a39f3a14e88.png)


2. By setting `transform=None` for the likelihood, there is no parameter transform to positive values, i.e. the raw noise level is used. If you're using `fit_gpytorch_scipy`, this is properly taken care of by forwarding the bound specified in the noise constraint to the optimizer (L-BFGS-B). However, since you're using `fit_gpytorch_torch`, the optimizer does not know how to handle explicit constraints, and during gradient descent the noise level will become negative, which causes all kinds of mayhem with the hyperparameters (though in this case this may actually be due to item 1.):
![Screen Shot 2019-08-13 at 8 56 30 AM](https://user-images.githubusercontent.com/1605878/62957078-f12e2780-bda8-11e9-9ea0-8430c7299725.png)
This kind of gotcha is one of the reasons I have been hesitant to fully support `fit_gpytorch_torch` in `joint_optimize` (c.f. #209).

**Comment by Tenoke** [comment]
Fwiw, I use torch there because in cases like this with scipy I seem to run into

```
RuntimeError: NaNs encounterd when trying to perform matrix-vector multiplication
```

Of course, the reason is the same and I currently mainly have those for testing as values like this should ideally be normalized otherwise.

**Comment by Tenoke** [comment]
I removed `fit_gpytorch_torch` after seeing this, but now I get 

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-7cc67c4712e4> in <module>()
      2 models = [('Basic GP, NEI', feval.fit_basic_gp_model, ucb)]
      3 
----> 4 acq_results = feval.test_models(models, d=12, num_starting=30, n_candidates=100, maximize=True, functions=['rastrigin'], scale=True)

18 frames
/usr/local/lib/python3.6/dist-packages/gpytorch/utils/linear_cg.py in linear_cg(matmul_closure, rhs, n_tridiag, tolerance, eps, stop_updating_after, max_iter, max_tridiag_iter, initial_guess, preconditioner)
    160     # Check for NaNs
    161     if not torch.equal(residual, residual):
--> 162         raise RuntimeError("NaNs encounterd when trying to perform matrix-vector multiplication")
    163 
    164     # Sometime we're lucky and the preconditioner solves the system right away

RuntimeError: NaNs encounterd when trying to perform matrix-vector multiplication
```

Constantly while modeling different functions again, so it's not really an option for me to use scipy, sadly.

**Comment by Balandat** [comment]
Did you change the normalization/standardization? Do you have a full reproable example for these latest failures?

**Comment by eytan** [comment]
@Tenoke , feel free to re-open this task with a reproducible example if @Balandat 's suggestion doesn't work for you.
