### ISSUE TITLE
[Feature Request] Make gen_batch_initial_conditions and optimize_acqf work with data that has more than 1111 dimensions

### ISSUE THREAD

**Issue by Tenoke** [pytorch/botorch#245]
# 🚀 Feature Request

Being able to use `gen_batch_initial_conditions` and `optimize_acqf` with data that has more than 1111 dimensions.

## Motivation

Currently you will get an error like this

```
gpapp_1  |   File "/app/fulloptim.py", line 96, in get_candidate
gpapp_1  |     acq_f, bounds=bounds, q=2, num_restarts=5, raw_samples=5,
gpapp_1  |   File "/opt/conda/lib/python3.6/site-packages/botorch/optim/optimize.py", line 136, in optimize_acqf
gpapp_1  |     options=options,
gpapp_1  |   File "/opt/conda/lib/python3.6/site-packages/botorch/optim/optimize.py", line 308, in gen_batch_initial_conditions
gpapp_1  |     seed=seed,
gpapp_1  |   File "/opt/conda/lib/python3.6/site-packages/botorch/utils/sampling.py", line 143, in draw_sobol_samples
gpapp_1  |     sobol_engine = SobolEngine(d, scramble=True, seed=seed)
gpapp_1  |   File "/opt/conda/lib/python3.6/site-packages/torch/quasirandom.py", line 47, in __init__
gpapp_1  |     "for SobolEngine is [1, {}]".format(self.MAXDIM))
gpapp_1  | ValueError: Supported range of dimensionality for SobolEngine is [1, 1111]
```

The only went to circumvent it is to build your initial conditions and pass them to `optimize_acqf`. 

## Pitch

Instead of an error, initial conditions could be created randomly (within the bounds) with something other than `draw_sobol_samples` when the dimensionality of the data is more than 1111 (sobol's limit)

**Comment by Balandat** [comment]
Sure, I can add a check here and use iid random points for initialization. May I ask what your use case for this is? I'm assuming you are using some kind of dimensionality reduction technique, since d>1111 is way to high to work with directly. Are you working in some latent lower-dim space internally? Just trying to understand your use case and if there is a better way to support it.

**Comment by Tenoke** [comment]
We are using GPs to solve high dimensional Bandit-type problems. Currently experimenting both with and without dimensionality reduction techniques.

It doesn't seem like GPs should always have a problem with working in arbitrarily high dimensions assuming you have enough resources and data. Although, again, if it underperforms we do have alternatives (e.g. SVGP with a Net that performs the dimensionality reduction)

**Comment by martinpfannemueller** [comment]
As my problem is related with this feature I comment here. I can also create a new issue if this is more desirable for your. We still do have the problem with the dimensions. The stacktrace:

```
Traceback (most recent call last):
  File "sim_dspl_bo_example.py", line 34, in <module>
    candidate = gp_dspl.get_candidate().squeeze()
  File "/home/user/coala-mdp/coala_al_eval/gp_dspl/packages/dspl_bo/dspl_bo.py", line 256, in get_candidate
    **params)
  File "/home/user/.local/lib/python3.6/site-packages/botorch/optim/optimize.py", line 148, in optimize_acqf
    options=options,
  File "/home/user/.local/lib/python3.6/site-packages/botorch/optim/initializers.py", line 98, in gen_batch_initial_conditions
    Y_rnd_curr = acq_function(X_rnd[start_idx:end_idx])
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/botorch/utils/transforms.py", line 170, in decorated
    return method(cls, X)
  File "/home/user/.local/lib/python3.6/site-packages/botorch/utils/transforms.py", line 141, in decorated
    return method(cls, X)
  File "/home/user/.local/lib/python3.6/site-packages/botorch/acquisition/monte_carlo.py", line 218, in forward
    samples = self.sampler(posterior)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/botorch/sampling/samplers.py", line 53, in forward
    self._construct_base_samples(posterior=posterior, shape=base_sample_shape)
  File "/home/user/.local/lib/python3.6/site-packages/botorch/sampling/samplers.py", line 230, in _construct_base_samples
    "SobolQMCSampler only supports dimensions "
botorch.exceptions.errors.UnsupportedError: SobolQMCSampler only supports dimensions `q * o <= 1111`. Requested: 1112
```

As far as I can tell when looking at your changes it should not be possible to call the SobolSampler anymore with a dimension higher than 1111. Any ideas? Thanks!

**Comment by Balandat** [comment]
Taking a step back, what's the problem you're trying to solve here? What acquisition function are you using / what are you optimizing over?

The dimension that the Sobol sampler requires in order to sample from a posterior is `qm`, where `q` is the number of points considered jointly and `m` is the outcome dimension (when using multi-output models). 

If in your scenario you're hitting the 1111 dimension limit it's likely that you're facing bigger issues than just using a different sampler, namely that you're optimizing some nasty function over a `qd`-dimensional space (with `d` the input feature dimension). 

That said, instead of the sobol sampler you could instead use an `IIDNormalSampler` for the acquisition function (see the MC acquisition function constructor docstrings for how to pass it in) that doesn't have the limitation (albeit at lower approximation quality of the acquisition function).

It's unfortunately not straightforward to change the existing sobol dimension limit, since the algorithm we use lives in pytorch core. I do not want to make `pyscenarios` a dependency for botorch, but if you want to give it a shot it should be straightforward to make a `MyOwnSobolQMCNormalSampler` class subclassing `SobolQMCNormalSampler` and replacing the [`draw_sobol_normal_samples`](https://github.com/pytorch/botorch/blob/master/botorch/sampling/samplers.py#L235-L241) method with your own that uses the alternative sampler. Should just be a few lines of code.

Of course one could also port over that sampler code into pytorch core... PRs for that are welcome :)

**Comment by martinpfannemueller** [comment]
Thanks a lot for your hints and explanations. In fact we are using now the `IIDNormalSampler` which works fine for us.
