### ISSUE TITLE
[Question] How does optimize_acqf interact with multi-task GP?

### ISSUE THREAD

**Issue by kzielnicki** [pytorch/botorch#325]
Thanks for the cool project! I'm particularly interested in the multi-task modeling capability in both Ax and botorch. I've been trying to understand a little better how botorch handles this scenario, and I've hit a little bit of a wall in my understanding. 

Specifically, how does acquisition function optimization interact with a multi-task GP model? When initializing a multi-task GP, we can specify which output tasks we'd like to model, eg `MultiTaskGP(train_X, train_Y, task_feature=-1, output_tasks=[1])`. If a single output task is specified, then the gpytorch connector will give us a multivariate normal, while if multiple output tasks are specified, then the gpytorch connector gives us a multi-task multivariate normal instead: https://github.com/pytorch/botorch/blob/master/botorch/models/gpytorch.py#L480-L489

Now let's throw in an acquisition function, eg `qNoisyExpectedImprovement`. Here we define a way to evaluate candidate points to test, based on the posterior of the fitted model. Meanwhile, optimize_acqf will use the acquisition function in generating and selecting candidate points based on the acquisition function's evaluation. 

So far so good! But here's the heart of the question, which I'm having a hard time understanding from the code: how are the candidate points determined when we have a multi-task GP? Are they optimized for expected performance on _all_ tasks or only on a specific task? Does this depend on what output tasks we specify in the model initialization (and thus, on whether we are estimating a multi-task multivariate posterior or not?) Empirically, it doesn't seem to, but I'm not sure where the smoking gun in the code is that determines this.

**Comment by Balandat** [comment]
Thanks for the detailed question. 

On the BoTorch end, if you have multiple `output_tasks` (or don't define any, in which case all tasks are modeled), say `m` of them, your posteriors will have `m` outputs. In essence, from that point on your model is a standard multi-output model, similar to when you use a `SingleTaskGP` on multi-dimensional targets `Y` (in which case the outcomes are modeled independently). 

So in order to optimize this, you'll need to do some scalarization of the outcome by passing an `Objective` into the acquisition function constructor. If you don't do that, then you don't get a scalar acquisition value back and (most likely) things break when trying to optimize the acquisition function (we should probably do some validation there that we indeed raise an actionable error in case no objective is passed to a multi-output model).

See this nb for illustration: [botorch_MTGP_objective.ipynb.txt](https://github.com/pytorch/botorch/files/3894750/botorch_MTGP_objective.ipynb.txt)

This is the BoTorch end, I'm not 100% sure off the top of my head how this is passed down to BoTorch via Ax, but I'll take a look. 

Hope this helps.

**Comment by Balandat** [comment]
Oh, and if your objective is to actually optimize a single task, then of course you should just define that task as the single `output_task`, since that will significantly reduce compute compared to (unnecessarily) predicting the joint posterior across tasks for each acquisition function evaluation.

**Comment by kzielnicki** [comment]
Thanks @Balandat! This is very helpful, especially the clear example notebook. On some further inspection, I think that this `.sum()` will implicitly sum the outputs during acquisition function optimization in the multi-output case if no scalarizing `Objective` is specified: https://github.com/pytorch/botorch/blob/master/botorch/gen.py#L112
Since this isn't what I want, I will just define the `output_task` as you suggest -- from your example it is clear that this will do the right thing to optimize for that task. As for the Ax case, it's harder to tell, so I will try this at the botorch level for now.

**Comment by Balandat** [comment]
Yeah there is the potential for something fishy to happen right now with the sum - I'm planning to add some validation for this so it results in a clear error. This will require #295 to be able to raise a proper error upon instantiation of the acquisition function. 

FWIW, assuming that the tasks are correlated, optimizing the sum of the acquisition values may not all be that terrible in practice. But of course we want to make sure this works properly.

**Comment by Balandat** [comment]
@kzielnicki, #331 adds validation for the outputs to avoid undefined behavior. Now you should get a clear error if you're trying to run an acquisition function without specifying an objective on a model with multiple output tasks.

Re the situation in Ax, the modebridge layer makes sure that the acquisition function is automatically be instantiated with the correct objective derived from the high-level description in the search space. The way the model works there is actually not very easy to follow (I had a hard time myself), since it uses the `ModelLIstGP` wrapper for multiple models. If `posterior` is called on that wrapper, under the hood the `posterior` methods of the `MultitaskGP` component models aren't called individually, but instead their `forward` methods are. 

I hope this clarifies things, feel free to re-open the issue if not.
