### ISSUE TITLE
[Bug] How to modify the code to optimize on integer-valued parameters?

### ISSUE THREAD

**Issue by aleczhanshi** [pytorch/botorch#381]
# 🐛 Bug

In the tutorial below, I wonder what the best/standard practice is to restrict the range of parameters to integers only. I hope it could be done without the help of ax. https://github.com/pytorch/botorch/blob/master/tutorials/closed_loop_botorch_only.ipynb

For example, I want to limit the first parameter to be one of these candidate integers (1, 2, 4, 6, 8, 12, 16, 32).

**Comment by eytan** [comment]
In general we recommend all BoTorch users to use BoTorch via Ax.  It should
be quite easy to swap in alternative models and acquisition functions.

IIRC in Ax we simply round to the nearest value.  This is similar to the
types of continuous relaxations done in integer programming.

If the number of possible values is low and you are doing sequential
(rather than parallel) optimization, one can also just optimize the
acquisition function, keeping the integer values fixed, for all
combinations of integers, and select the design point that with the highest
utility.  This would be the most optimal.

**Comment by aleczhanshi** [comment]
Hi Eytan, thanks for the quick reply. In terms of Ax, how should we get the (current best set of) values for the optimized parameters and the objective values? For example, in the tutorial below, it does not print out anything that can be understood.

https://github.com/pytorch/botorch/blob/master/tutorials/custom_botorch_model_in_ax.ipynb
