### ISSUE TITLE
[Bug] Input equality constraints violated

### ISSUE THREAD

**Issue by aleczhanshi** [pytorch/botorch#432]
Hi there,

I've run into some situations where the input constraints break occasionally. In particular, I'm following the constrained BO tutorial (https://botorch.org/tutorials/closed_loop_botorch_only) and below is my code for specifying input constraints, where I do have inequality constraints though.

```python
equality_constraints = [(torch.tensor([4, 5, 6, 7, 8]), torch.tensor([1]*5), 8.0)]
candidates, _ = optimize_acqf(
    acq_function=acq_func,
    bounds=bounds,
    q=BATCH_SIZE,
    equality_constraints=equality_constraints,
    inequality_constraints=inequality_constraints,
    num_restarts=10,
    raw_samples=512,  # used for intialization heuristic
    options={"batch_limit": 5, "maxiter": 200},
)
```

Once in a while, I got parameters 4-8 that adds up to 9.0 or even >10.0, which is supposed to be 8.0. Could you help explain why this happens and how I should work around this. Thanks!

**Comment by Balandat** [comment]
Do you have a full example with synthetic data where this happens? Are you sure the feasible set is non-empty? 

This could be an issue with our heuristic for generating initial conditions in the presence of these constraints, I can take a look at that.

**Comment by JianJieLin** [comment]
I am a little confused since optimize_acqf supports the inequality and equality constraints, but the example in "closed_loop_botorch_only" did not use the feature. 
By using the same structure in "closed_loop_botorch_only", I try to implement the constrained example: "Rosenbrock function constrained" with two inequality constraints.  Do you have any idea how to define the function "weighted_obj" and other functions? 
thank you for your help in advanced

**Comment by Balandat** [comment]
@JianJieLin I think you might be confusing parameter (input) constraints and outcome constraints here? Outcome constraints are constraints on black-box to-be-modeled outcomes (they would use sth like weighted_obj), while parameter constraints are bounds imposed directly on the optimization domain.

**Comment by iTakeshi** [comment]
I'm facing a similar issue as @JianJieLin and confused by the difference between
> parameter (input) constraints and outcome constraints

Are there any docs or resources explaining them?

**Comment by Balandat** [comment]
I'll work on putting up some docs explaining this in more detail. In the meantime,
- parameter constraints are constraints on the inputs / the features. That is, rather than just living inside a bounding box, inputs may be further constrained by linear (in)equality constraints. This doesn't really affect the modeling directly, and is used when generating candidates in the form of `inequality_constraints` and `equality_constraints` args to `optimize_acqf`. 
- outcome constraints are constraints on "black-box" outcomes that need to be modeled just like the objective. This is what's done with the L1 toy constraint in the https://botorch.org/tutorials/closed_loop_botorch_only tutorial.

Parameter constraints have nothing to do with observed outcomes, and outcome constraints have nothing to do with parameter constraints. You can have parameter constraints but no outcome constraints, outcome constraints but no parameter constraints, both, or neither. 

Aside: Apparently we don't generate the initial conditions properly on that restricted feasible set but instead inside the bounding box. Usually the optimizer should be able to deal with this but it's certainly suboptimal, so we we'll need to fix this (should be straightforward using #592).

**Comment by iTakeshi** [comment]
Thank you for the quick and comprehensive response. It solved my confusion.

**Comment by Balandat** [comment]
We've landed changes that properly generate initial conditions which should fix the issues with input equality constraints violations. Please re-open if the do persist on the most recent release.
