### ISSUE TITLE
gpytorch lanczos.py problem: failed to converge

### ISSUE THREAD

**Issue by goodnamegood** [pytorch/botorch#451]
I'm running the tutorial for qNEI (the tutorial is this one: https://botorch.org/tutorials/closed_loop_botorch_only) and get the following error while doing the optimization:
RuntimeError: symeig_cpu: For batch 0: the algorithm failed to converge; 2 off-diagonal elements of an intermediate tridiagonal form did not converge to zero. Any help? Thanks!

**Comment by Balandat** [comment]
Sorry this must have really fallen off the radar - this is typically a sign of numerical issues. My suspicion is that this in fact might have been caused by NaNs in some gradient computations. We instrumented this in #688, which should catch these problems. We also made quite a few other changes since then, so this should mostly be resolved.
