### ISSUE TITLE
[Question] candidate_set for qMaxValueEntropy

### ISSUE THREAD

**Issue by roshni-kamath** [pytorch/botorch#483]
Does it make sense to use the train_X as candidate_set in case of qMaxValueEntropy and use the updated train_X for every iteration?

**Comment by Balandat** [comment]
So `candidate_set` is the set of points at which to draw (joint) posterior samples in order to sample from the maximum value of the posterior (there are other ways to implement this max-value sampling, but this is how `qMaxValueEntropy` does it).

Ideally, `candidate_set` is a relatively dense set of points in the design space (a grid, or a random sample). `train_X` by itself is typically not a particularly good choice as it often only consists of a small number of points, and is usually clustered in the search space. Instead, one typically uses a set of randomly sampled points (see [the MVES tutorial](https://botorch.org/tutorials/max_value_entropy#3.-Defining-the-MES-acquisition-function)). It probably would not be a bad idea to augment that set with the `train_X` points, but the `train_X` points alone likely won't work very well.

**Comment by roshni-kamath** [comment]
Thank you very much for clarifying
