### ISSUE TITLE
botorch or gaussian model support C++ paltform (or the way of "torch.jit.trace" )

### ISSUE THREAD

**Issue by leobest1101** [pytorch/botorch#512]
Dear sir:
    Thank you very for your botorch project, it is a very good project.
    I have a question when deploy the model?
    Does the botorch(gytorch) suport the c++ environments? Like the way of "torch.jit.trace" (https://pytorch.org/docs/stable/jit.html).
    When I used the "torch.jit.trace" to save the botorch(gytorch) mode, there are many problem? 
    Could you help me to provided some other ways to deploying the model in c++?

Thank you very much for your help.

**Comment by Balandat** [comment]
You can trace gpytorch models, see e.g. the example [here](https://github.com/cornellius-gp/gpytorch/blob/master/examples/08_Advanced_Usage/TorchScript_Exact_Models.ipynb). Since most botorch models are wrappers around gpytorch models there shouldn't be any major issues with that.

If you're trying to do BayesOpt with traced objects (I wouldn't), things would become quite a bit more complicated.

**Comment by eytan** [comment]
Can you talk about the motivation For doing things in C++? Typically BO is
used for sequential optimization of very expensive function evaluations and
so the latency requirements for BO tend to be generous enough to afford
working in python. And of course, in a production setting, one could keep a
persistent process going and just make RPC calls to the thread (say, if
parts of the backend were written in C++).

Hope this helps!

**Comment by Balandat** [comment]
Closing this out for now. Feel free to open a new Discussion item on https://github.com/pytorch/botorch/discussions if this is still something you'd like to do (and have good reasons for).
