### ISSUE TITLE
Joint candidate generation

### ISSUE THREAD

**Issue by bazpasha** [pytorch/botorch#572]
Hello!

I've got confused by joint candidate generation. In the paper which I've read ([Constrained Bayesian Optimization with Noisy Experiments](https://projecteuclid.org/download/pdfview_1/euclid.ba/1533866666), p. 499, eq. 3) the batch of candidates of size N is generated in the following fashion: rather than optimizing an acquisition function separately N times, we generate candidates sequentially, optimizing the expectation of the acquisition function (over predictions of the objective for the candidates we have already generated).

[In the documentation](https://botorch.org/docs/optimization#joint-vs-sequential-candidate-generation-for-batch-acquisition-functions), however, it seems that we solve the problem of optimizing an acquisition function N times (independently).

So my question is whether I've got it correctly. :)
And if yes, what do the candidates correspond to? To different local minima of the acquisition function (obtained by an optimizator)?

**Comment by bazpasha** [comment]
I think that now I've got it. So, an acquisition functions in BoTorch can be applied to q candidates and return a single scalar value. Also there are two possible ways of searching for the candidates: sequential (and it corresponds to the equation from the article above) and non-sequential (it is when all candidates are optimized at once).

But now I have a different question. For acquisition functions like qEI, why is it a good idea to use the non-sequential mode? As long as x_1 (for example) is the optimum for EI, I can set all other candidates x_2, ..., x_q at random and it won't affect the value of the acquisition function, will it? It is because we have "max" over y(x_i) in the qEI equation.

Why do we need the joint mode then? Are there any acquisition functions for which it is a mode to use? Is it true that I only need to use the sequential mode of optimization with simple acquisition functions like qEI, qUCB etc.

**Comment by Balandat** [comment]
> So, an acquisition functions in BoTorch can be applied to q candidates and return a single scalar value. Also there are two possible ways of searching for the candidates: sequential (and it corresponds to the equation from the article above) and non-sequential (it is when all candidates are optimized at once)

You got it right. We evaluate the *joint* value of a set of candidates. 

> But now I have a different question. For acquisition functions like qEI, why is it a good idea to use the non-sequential mode? As long as x_1 (for example) is the optimum for EI, I can set all other candidates x_2, ..., x_q at random and it won't affect the value of the acquisition function, will it? It is because we have "max" over y(x_i) in the qEI equation.

So this argument holds only if you don't apply the expectation. Note that `E[max(a, b)] != max(E[a], E[b])` in general, which is why considering things jointly is important. 

Also, note that both "sequential" and "joint" optimization modes try to optimize the joint value of the q candidates, but in different ways. Joint optimization in some way is the "proper" way of doing this (but results in a higher-dim and harder optimization problem), while the sequential conditioning variant makes some approximations to try to achieve the same thing using a greedy algorithm (which can be more tractable, especially for large q). You can use submodularity arguments to show that sequential is generally not too bad, see e.g. [this paper](http://papers.nips.cc/paper/8194-maximizing-acquisition-functions-for-bayesian-optimization).

**Comment by bazpasha** [comment]
Thank you very much for the detailed answer!
