### ISSUE TITLE
[Bug]input_transform for MultiTaskGP does not work as expected

### ISSUE THREAD

**Issue by lirnli** [pytorch/botorch#629]
# 🐛 Bug

InputTransform is not compatible with MultiTaskGP, because the last dimension in train_X is task_feature, which should not be normalized.

```
    def forward(self, x: Tensor) -> MultivariateNormal:
        x = self.transform_inputs(x) # This transform should exclude the last column, which is task_feature.
        x_basic, task_idcs = self._split_inputs(x) 
        # Compute base mean and covariance
        mean_x = self.mean_module(x_basic)
        covar_x = self.covar_module(x_basic)
        # Compute task covariances
        covar_i = self.task_covar_module(task_idcs)
        # Combine the two in an ICM fashion
        covar = covar_x.mul(covar_i)
        return MultivariateNormal(mean_x, covar)
```

**Comment by Balandat** [comment]
I see what you're saying. A lot of input transforms (`Round`, `Log10`, `Warp`) will actually work since you can specify which indices to transform, but this is not exposed in `Normalize`. 

The easiest way to fix this would probably be to add a `indices: Optional[List[int]] = None` argument to the `Normalize` constructor and then only normalize the specified dimensions. The default `None` would then normalize all dimensions, so no change in default behavior. Does this sound reasonable?

**Comment by saitcakmak** [comment]
Closing this since `Normalize` now accepts an `indices` argument.
