### ISSUE TITLE
Code for empirical asymptotic convergence rates in BoTorch paper

### ISSUE THREAD

**Issue by chengyl2020** [pytorch/botorch#653]
# 🐛 Bug

please, i want to know how to find the code to get the result below?
![image](https://user-images.githubusercontent.com/62138247/103275192-97121e80-49fe-11eb-9103-e1c42a9a8f5c.png)

**Comment by Balandat** [comment]
So I went back and re-ran the code for generating this, and I realized that the results for "re-sampling" are quite a bit better since I last generated the results for the paper. This is likely due to improvements for the convergence criterion we use for the stochastic optimization. However this doesn't change the main results or the story of the paper.

I will update the final version of the paper with these new figures / values. I used the following notebook to generate the results: 
[MC_qMC_analytic_qualitative_with_Adam_updated_v3.ipynb.txt](https://github.com/pytorch/botorch/files/5762617/MC_qMC_analytic_qualitative_with_Adam_updated_v3.ipynb.txt)
