### ISSUE TITLE
Access to X values in an Objective transfrom

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#663]
Dear botorch developers,

I have a question regarding the `objective` module which can be used to transform model outputs into a single scalar on which the actual optimization is then performed. In my case the optimization target is actually a function of the model output and some of the model input parameters. For this reason, I would like to have access to the model inputs in the `objective` module. 

I know that I could also perform the transformation in advance and train to the transformed output, but this would mean that the model has to learn something which is known in closed form. Furthermore I need the untransformed model output also for other reasons.

I hope this request is somehow clear, if not I can try to describe an example use case scenario, in which this could be helpful.

Best,

Johannes

**Comment by qingfeng10** [comment]
Hey Johannes,

Thanks for your interest! An example use case scenario will be very useful, in case I misunderstood! 

Here is my understanding and the corresponding answer.  Say you have model output `f(x)`. Your optimization target is a composite function `g(f(x))` in which `g` is known. In this case, you might find the `GenericMCObjective` useful e.g. [here](https://github.com/pytorch/botorch/blob/8a36c80743cc76c6303f7e65fa618a1d9508d1f4/botorch/acquisition/objective.py#L161).   Let me know if you have further questions.

**Comment by Balandat** [comment]
Hi @johannes, this is an interesting question. Currently, `MCAcquisitionObjective` only takes `samples` (samples from the model posterior) as an arg: https://github.com/pytorch/botorch/blob/master/botorch/acquisition/objective.py#L77, so it's not just plug and play. 

One way to achieve what you suggest is to extend the API with an `X: Optional[Tensor]=None` argument so that the objective can also take in the input `X`. This would allow to straightforwardly compute the objective on the sample-level inside the acquisition function. E.g. we'd just replace https://github.com/pytorch/botorch/blob/master/botorch/acquisition/monte_carlo.py#L160 with `obj = self.objective(samples, X=X)`. 

Would that address your use case? I can put together a PR for this it that would be helpful.

**Comment by johannes** [comment]
I guess you didn't want to highlight me :-) But keep up the good work on your project!

**Comment by Balandat** [comment]
ugh sorry about that. I think GitHub needs a TagRoulette feature :)

This was of course meant to be directed at @jduerholt

**Comment by jduerholt** [comment]
Hi @Balandat,

thanks for your quick response. What you describe is exactly what I need. But the `obj = self.objective(samples, X=X)`, has to be changed not only in `qExpectedImprovement` but also for the other MC Acquisition functions, or?

I would be very thankful if you can put together a PR for this.

Best,

Johannes

**Comment by Balandat** [comment]
> Thanks for your quick response. What you describe is exactly what I need. But the obj = self.objective(samples, X=X), has to be changed not only in qExpectedImprovement but also for the other MC Acquisition functions, or?

Correct. Should be relatively straightforward though.
