### ISSUE TITLE
The multi-fidelity setting of MF-MVES

### ISSUE THREAD

**Issue by hanjq17** [pytorch/botorch#673]
## Description

Thanks for the wonderful package!

My problem is about how to use the MF-MVES acquisition function under a proper multi-fidelity setting of the model. According to the original paper of MF-MVES, the model requires a kernel which works between data points of different fidelities. If I want to use the MF-MVES acquisition function in the BO loop, which model should I use accordingly?

In the code, an example is given as follows:
Example:
        >>> model = SingleTaskGP(train_X, train_Y)
        >>> candidate_set = torch.rand(1000, bounds.size(1))
        >>> candidate_set = bounds[0] + (bounds[1] - bounds[0]) * candidate_set
        >>> MF_MES = qMultiFidelityMaxValueEntropy(model, candidate_set)
        >>> mf_mes = MF_MES(test_X)

Can a model of the class SingleTaskGP properly model the relationship between different fidelities? Or should I use the model from SingleTaskMultiFidelityGP?

Besides, how does the argument 'expand' work in this function? i.e., what's the meaning of 'trace observations' ?

Many Thanks!

**Comment by Balandat** [comment]
> If I want to use the MF-MVES acquisition function in the BO loop, which model should I use accordingly?

At a basic level, MF-MVES should work with any model that can properly model the outcomes jointly over the regular and fidelity parameters. A general `SingleTaskGP` in principle can do that, However, rather than just using a standard (say RBF or Matern) kernel, adding inductive biases by using a more specialized kernel can significantly improve modeling. I would suggest to start  with `SingleTaskMultiFidelityGP`, we should probably update that usage example.

>  how does the argument 'expand' work in this function? i.e., what's the meaning of 'trace observations' ?

This is for dealing with settings in which one knows that one can obtain partial ("trace") observations from the evaluation, e.g. points on the learning curve of a ML training job. See e.g. https://arxiv.org/pdf/1903.04703.pdf. `expand` is basically a way of injecting which other fidelities one expects to observe during the evaluation. At this point this is an experimental feature and not as well tested as many other parts of the package.

**Comment by hanjq17** [comment]
Thanks for the quick and constructive reply! 
Now I realize that a key difference between `SingleTaskGP` and `SingleTaskMultiFidelityGP` lies in the kernel, which is open to implement if I find my situation slightly different from the fidelity settings described in https://arxiv.org/pdf/1903.04703.pdf, e.g., discrete vs continuous. A key ingredient of MF-MVES calls for the covariance matrix between m and M (target fidelity) after projected, which can work well as long as the kernel is well-defined, including both `SingleTaskGP` and `SingleTaskMultiFidelityGP`, and other GP with user-defined kernels that extends the class `SingleTaskGP`, if I'm not missing anything.
Besides, it would be very much appreciated if a usage example regarding MF-MVES could be updated. 
Again, many thanks!
