### ISSUE TITLE
Output subsetting fails when using a custom likelihood

### ISSUE THREAD

**Issue by RaulAstudillo06** [pytorch/botorch#751]
## Issue description

Output subsetting fails when using a custom likelihood.

## Code example

        import torch
        from botorch.models import SingleTaskGP
        from gpytorch.constraints.constraints import Interval
        from gpytorch.likelihoods.gaussian_likelihood import GaussianLikelihood
        
        train_X = torch.tensor(
                    [[0.0, 0.1], [0.2, 0.5], [0.8, 1.0]]
                )
        train_Y = torch.tensor([[1.0, 1.0], [2.0, 3.0], [3.0, 5.0]])
        
        likelihood = GaussianLikelihood(
                    batch_shape=train_Y.shape[:-2],
                    noise_constraint=Interval(lower_bound=1e-5, upper_bound=1e-3),
                )
        
        model = SingleTaskGP(
                    train_X=train_X,
                    train_Y=train_Y,
                    likelihood=likelihood,
                )
        
        model.subset_output(idcs=[0])

## Error message

Dimension out of range (expected to be in range of [-1, 0], but got -2)
IndexError                                Traceback (most recent call last)
<ipython-input-2-c1c243d14f97> in <module>
     20         )
     21 
---> 22 model.subset_output(idcs=[0])
/mnt/xarfuse/uid-231925/5bf2a995-seed-nspid4026531836-ns-4026531840/botorch/models/gpytorch.py in subset_output(self, idcs)
    450             if full_name in subset_batch_dict:
    451                 idx = subset_batch_dict[full_name]
--> 452                 new_data = p.index_select(dim=idx, index=tidxr)
    453                 if m == 1:
    454                     new_data = new_data.squeeze(idx)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got -2)

**Comment by Balandat** [comment]
The issue is that if that in the multi-output case `SingleTaskGP` shifts the batch dimensions around internally to represent the outputs as batch dimensions. This means the batch shape internal to the model is actually a different one from the batch shape of the training data. The default likelihood is instantiated with the correct batch shape that can be obtained from the model (`_aug_batch_shape` attribute): https://github.com/pytorch/botorch/blob/master/botorch/models/gp_regression.py#L108-L116

Subsetting with a custom likelihood also works if you use the proper batch shape. Of course the `_aug_batch_shape` attribute is not available instantiation, but you can get it using the static method `get_batch_dimensions` (defined on the superclass).

See here for an example: [debug_issue_751.ipynb.txt](https://github.com/pytorch/botorch/files/6167652/debug_issue_751.ipynb.txt)

What this also means is that if you did not subset your model and just used it with the batch shape from your example this would have done something potentially wrong / ill defined...

**Comment by Balandat** [comment]
We can probably be better about documenting this in the class docstring, but this unfortunately quite hard to handle generally.

**Comment by RaulAstudillo06** [comment]
Thanks, Max! I wasn't aware that augmented batch size absorbed the output dimension.
