### ISSUE TITLE
Question: Handling of bounds

### ISSUE THREAD

**Issue by preritt** [pytorch/botorch#761]
Hi,
I am not sue how the transformation of data works. When we optimize the acquisition, do the candidate solutions need to be unnormalized to get back to the original scale. 

Does `candidates_q2 ` have the same scale as `train_inputs_raw_GA_torch ` or needs to be transformed once we obtain the solution? 

Is the line below required?

`candidates_q2_temp = unnormalize(candidates_q2, bounds = bounds) 
`
These are my bounds:

```
tensor([[[-0.0160, -0.0160, -0.0163, -0.0160, -0.0079, -0.0160, -0.0079,
          -0.0328, -0.0161, -0.0160, -0.0161, -0.0080, -0.0161, -0.0160,
          -0.0081, -0.1066]],

        [[ 1.0080,  1.0080,  1.0244,  1.0080,  1.0079,  1.0080,  1.0079,
           1.0164,  1.0161,  1.0080,  1.0161,  1.0160,  1.0161,  1.0080,
           1.0242,  1.7316]]], dtype=torch.float64)
```

```
  model = SingleTaskGP(train_X=train_inputs_raw_GA_torch, train_Y=train_outputs_raw_GA_torch,likelihood=likelihood
                       )

  acq_func = qExpectedHypervolumeImprovement(
        model=model,
        ref_point=reference_point_raw_transformed,  # use known reference point 
        partitioning=partitioning,
        sampler=sampler,
    ) 

    candidates_q2, acq_value = optimize_acqf(
          acq_function=acq_func,
          bounds=bounds,
          q=BATCH_SIZE,
          num_restarts=NUM_RESTARTS,
          raw_samples=RAW_SAMPLES,
          options={"batch_limit": 5, "maxiter": 200, "nonnegative": True},
          sequential=True,
      )
```

Thanks

**Comment by saitcakmak** [comment]
Hi @preritt. When you use `optimize_acqf` with `bounds`, the resulting `candidates_q2` will be restricted to `bounds`, meaning that it can take any value in that satisfies `bounds`. So, I don't see why you would need to use `untransform`.

>Does candidates_q2 have the same scale as train_inputs_raw_GA_torch or needs to be transformed once we obtain the solution?

So, assuming `train_inputs_raw_GA` is defined over the same bounds you provide to `optimize_acqf`, the answer is yes, and you do not need to untransform `candidates_q2`. 

To give an example of how I personally use transforms in BoTorch, I typically set my bounds as `[0, 1]^n`. In this case, any solution returned by `optimize_acqf` (call this `X`) will also be in `[0, 1]^n`, which may not be the same as the domain of the `function` I am optimizing. So, when evaluating the `function`, instead of calling `function(X)`, I will call `function(unnormalize(X, function.bounds)`, which transforms `X` into the function domain before evaluation.

BoTorch also has other transforms that are intended to make the training inputs better compatible with the default priors (some have other uses too), used by passing the `input_transform` and `outcome_transform` arguments to the model constructor, e.g., `model = SingleTaskGP(train_X, train_Y, input_transform=normalize(d=2), outcome_transform=Standardize(m=1))`. These work under the hood when you call the model, and do not require you to do any transforms manually.

**Comment by preritt** [comment]
Thank you. That was very clear and helpful. 
This is a great library!


Thanks,
Prerit

**Comment by Balandat** [comment]
Thanks for the great explanation, @saitcakmak

**Comment by theo-brown** [comment]
@saitcakmak is there any particular reason why setting the bounds to `[0,1]^n` and unnormalizing manually to `[upper, lower]` (for example) is preferable to setting the bounds to `[upper, lower]` in `optimize_acqf` directly?

Just noticed that this is the way the tutorials do it too, and wondering what the reason was.

**Comment by saitcakmak** [comment]
> is there any particular reason why setting the bounds to [0,1]^n and unnormalizing manually to [upper, lower] (for example) is preferable to setting the bounds to [upper, lower] in optimize_acqf directly?

The reason we normalize the bounds (either manually or by using `Normalize` input transform) is that the default model hyper parameters (particularly for lengthscales) are designed with this assumption. For `optimize_acqf`, how you normalize the data and what bounds you pass in doesn't really matter. These days, I just use the `Normalize` input transform and pass in `[lower, upper]` rather than dealing with manually normalizing and unnormalizing the inputs. 

> Just noticed that this is the way the tutorials do it too, and wondering what the reason was.

The tutorials that do manual normalization were likely written (or modified from others that were written) before the input transforms became mainstream in BoTorch.
