### ISSUE TITLE
[Bug] qNegIntegratedPosteriorVariance with input transforms

### ISSUE THREAD

**Issue by soerenjalas** [pytorch/botorch#899]
# 🐛 Bug
Hi first off thanks a lot for this fantastic tool. Not sure if this is a bug or just misusage on my side…
I've observed an odd behaviour when I tried to use qNegIntegratedPosteriorVariance with a FixedNoiseGP that uses an `input_transform`. It seems that `optimize_acqf` returns only suggestions within [0,1]^d, so in the "post-transform" parameter space. When using no `input_transform` (i.e. non-optimal priors?) the suggestions are given over the desired bounds. Also when using a different acquisition function everything looks okay. Do I need to do an explicit back-transformation of the suggested parameters?

The plots below show the two scenarios (blue dots are the samples, orange are the mc_points for NIPV). With `input_transform` all but the first 2 random samples are in the same spot.

Thanks!

![nipv_trans](https://user-images.githubusercontent.com/10922951/129027408-e0ba2327-db1a-4348-a85d-263337070224.png)
![nipv_notrans](https://user-images.githubusercontent.com/10922951/129027417-0080a13c-00d5-4c1c-9d3a-0c7ef2712e68.png)

## To reproduce

** Code snippet to reproduce **
```python
test_func = Branin()
ndim = 2
xmin, xmax = (-5., 10.)

l_bounds = [xmin]*ndim
u_bounds = [xmax]*ndim
sampler = qmc.Halton(d=ndim, scramble=False)
sample = sampler.random(n=1024)
sample = qmc.scale(sample, l_bounds, u_bounds)
mc_points = torch.from_numpy(sample)

X_data = torch.from_numpy(np.random.rand(2,2))*(xmax-xmin)+xmin
y_data = test_func(X_data).reshape(-1,1)
bounds = torch.tensor([[xmin]*ndim,[xmax]*ndim])

maes = []
for i in tqdm(range(20)):
    y_noise = torch.ones_like(y_data)*1e-6
    model = FixedNoiseGP(X_data, y_data,y_noise,
                         #input_transform=None,
                         input_transform=Normalize(ndim, bounds=bounds),
                         outcome_transform=Standardize(1),
                         )
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_model(mll)
    acq_func = qNegIntegratedPosteriorVariance(model=model,mc_points=mc_points)
    #acq_func = qNoisyExpectedImprovement(model, X_baseline=X_data)
    
    candidates, _ = optimize_acqf(
        acq_function=acq_func,
        bounds=bounds,
        q=1,
        num_restarts=10,
        raw_samples=512,  # used for intialization heuristic
    )
    new_x = candidates.detach()
    exact_obj = test_func(new_x).unsqueeze(-1)
    X_data = torch.cat([X_data, new_x])
    y_data = torch.cat([y_data,exact_obj])
```

## System information

**Please complete the following information:**
-   botorch 0.5.0
-  gpytorch 1.5.0
-  pytorch 1.9.0+cu102
-  Linux

**Comment by Balandat** [comment]
Is this on the botorch 0.5.0 release or on the current master?

@saitcakmak since you've worked extensively on the input transforms recently would you mind taking a look at this one?

**Comment by saitcakmak** [comment]
@soerenjalas thanks for pointing this out. It is indeed a serious bug and extends beyond the `FixedNoiseGP` you're using here. I'll put up a fix for this shortly.

Here is the issue: If using `input_transform`, `train_inputs` are stored on the transformed scale, i.e., something like `train_inputs = [transform_inputs(train_X)]`. In `fantasize` call, we calculate the model predictions for the given `X` (which uses the transforms under the hood) and add `X` and `fant_Y` to the training data. Since the `train_inputs` are on the transformed scale, we need to add `transform_inputs(X)` and not `X` itself. Turns out, we currently add `X` directly, leading to the bug seen here. (This does not happen with `fant_Y` as those get transformed later)

P.s.: A quick BoTorch hint that may save you a few lines in the future. BoTorch has convenient wrappers for Sobol sequences, which I assume you're familiar with since you're using Halton here. So, you could replace
```
l_bounds = [xmin]*ndim
u_bounds = [xmax]*ndim
sampler = qmc.Halton(d=ndim, scramble=False)
sample = sampler.random(n=1024)
sample = qmc.scale(sample, l_bounds, u_bounds)
mc_points = torch.from_numpy(sample)

X_data = torch.from_numpy(np.random.rand(2,2))*(xmax-xmin)+xmin
y_data = test_func(X_data).reshape(-1,1)
bounds = torch.tensor([[xmin]*ndim,[xmax]*ndim])
```
with
```
from botorch.utils.sampling import draw_sobol_samples

bounds = torch.tensor([[xmin]*ndim,[xmax]*ndim])
mc_points = draw_sobol_samples(bounds=bounds, q=1, n=1024).squeeze(-2)

X_data = draw_sobol_samples(bounds=bounds, q=1, n=2).squeeze(-2)
y_data = test_func(X_data).reshape(-1,1)
```
which should produce qualitatively similar qMC samples with minimal effort.

**Comment by Balandat** [comment]
Btw, nice to see you using `scipy.stats.qmc`. You could alternatively also use `qmc.Sobol` (which I contributed :)), functionally it should be exactly equivalent to `torch.quasirandom.SobolEngine` that botorch uses.
