### ISSUE TITLE
[Question] Difference in variance when we use GPyTorch and BoTorch

### ISSUE THREAD

**Issue by mohammad-saber** [pytorch/botorch#923]
Hi, thank you for sharing your great work. 

I have a question about variance that we get by model fitting. 

As an example, when I use the following code:

```
gp = SingleTaskGP(train_X, train_Y)
mll = ExactMarginalLogLikelihood(gp.likelihood, gp)
fit_gpytorch_model(mll)
```

I can get variance of test set by:

`variance = gp.posterior(X_test).variance
`

When I use `GPyTorch`, there are two ways to get variance. Following the [documentation](https://docs.gpytorch.ai/en/v1.1.1/examples/01_Exact_GPs/Simple_GP_Regression.html), after fitting model, I can get variance of test set by one of the following methods:

Method 1:

```
f_preds = model(test_x)
f_var = f_preds.variance
```

Method 2 (using likelihood): 

```
y_preds = likelihood(model(test_x))
y_var = y_preds.variance
```

The values of `f_var` and `y_var` are different. 

I would like to ask when I get variance in BoTorch by :

`variance = gp.posterior(X_test).variance
`

Is it equivalent to GPyTorch Method 1 or Method 2?

**Comment by saitcakmak** [comment]
Hi @mohammad-saber. BoTorch `posterior` calls typically have an `observation_noise` argument that defaults to `False`. So, the variance you get with `gp.posterior(X_test).variance` is equivalent to Method 1 (It may have a different shape and would have input / outcome transforms applied if they're used). If you instead use `gp.posterior(X_test, observation_noise=True).variance`, then this would be equivalent to the Method 2.

**Comment by mohammad-saber** [comment]
Thank you very much for your help. 
I was wondering which one gives better estimate of variance?

**Comment by saitcakmak** [comment]
That depends on what you mean by "better". The first method gives the predictions for the true function value - this is commonly referred to as the predictive (posterior) distribution. The second method adds the observation noise to this, so the result is the model prediction for what a new observation from a given point may look like (including the observation noise). 

In BO, we typically use the first method since we're interested in predicting the true function but the second method also comes into play, e.g., in knowledge gradient, when we are generating fantasy models (where we condition the model on a fantasized noisy observation).

**Comment by mohammad-saber** [comment]
I understand. Thanks for your help.
