### ISSUE TITLE
How do I use float input to optimize_acqf_discrete?

### ISSUE THREAD

**Issue by sambitmishra98** [pytorch/botorch#942]
I am trying to use `optimize_acqf_discrete`. The following is my code. I am not able to figure out how to give inputs as float numbers.
[Google Colab Code](https://colab.research.google.com/drive/1cfCEm7tmyA6VjCqk9QjGDPxR-eEW30ze?usp=sharing)
Is this a limitation of the function? Am I expected to use `optimize_acqf_mixed`?

**Comment by Balandat** [comment]
The issue here is fundamentally that numpy and torch have different default data types: numpy uses float64 but torch uses float32. Since `train_X` is float32 your model is float32, but when you create the fidelity meshgrid in numpy this is done in float64 which is then retained by the `torch.tensor` call, resulting in the dtype mismatch deep in the stack that you're seeing. 

You have two options:
1. Set up your model in float64 (either by specifying this for the input tensors or by changing the default torch dtype)
2. Add a `.astype(np.float32)` to the `meshgrid_discrete_fidelities(fidelities)` call

If you're working with the smaller data regime and do not require heavy GPU acceleration option 1 is much preferred, since GP inference requires solving often relatively poorly conditioned linear systems which can cause a lot of numerical headaches in float32.

**Comment by sambitmishra98** [comment]
Thanks a lot for your detailed response! 
I successfully used the second option you mentioned, since in the end I am going to use single precision arrays for optimisation.
