### ISSUE TITLE
Bayesian optimisation with Integers as candidates.

### ISSUE THREAD

**Issue by sambitmishra98** [pytorch/botorch#950]
Given a dataset of integer-type `train_X` and float-type `train_Y`, I want to generate the next candidate using Botorch. 

I haven't been able to find a function in the API which does this. `optimize_acqf_mixed` and `optimise_acqf_discrete` expect you to provide a list of possible candidates too. Is there a way to give the upper bound and lower bound and expect an candidate which has only integer values?

I am currently running `optimize_acqf` for floating numbers and am rounding up the candidates to the nearest integer. This is however giving very bad results after a few steps of optimisation. If I run the code in a while loop to obtain the next best unique candidate, the optimisation process does not explore the solution space anymore and stagnates.

**Comment by sambitmishra98** [comment]
I am using dataset made of one float (bound between 1 and 7) and 7 integer values (bound between 1 and 3) as train_X, and a float value as train_Y.
I also wish to restrict the first float input to round up to the first decimal place, but I guess the only way to do that is again by defining the set of possible discrete inputs for it {1, 1.1, 1.2, .... 7} which will be much slower than just defining it as float.
I checked `optimize_acqf_mixed` to find that the function ultimately calls `optimize_acqf` with the given set of possible discrete choices.

**Comment by Balandat** [comment]
3^7 = 2187, so enumerating the discrete values and solving a continuous problem for each is probably not a great idea here. Optimizing over this kind of search space with many discrete variables where the cardinality quickly explodes is quite challenging and there aren't any great general solutions (at least that I'm aware of). Since there is only a single float, my approach here would probably be to also discretize the float (to say int values only), evaluate all 2187*7 ~ 15K combinations using `optimize_acqf_discrete`, pick off the top say ~40 or so solutions, and then use the values of the int parameters of those to run `optimize_acqf_mixed` to fine-tune the continuous solution. 

> I also wish to restrict the first float input to round up to the first decimal place, but I guess the only way to do that is again by defining the set of possible discrete inputs for it {1, 1.1, 1.2, .... 7} which will be much slower than just defining it as float. (correct me I am wrong here)

In general in that case I wouldn't worry about the rounding during the acquisition function optimization - the resolution is sufficiently high that the issues from rounding after the fact should be minor. However, given that the cardinality of the discrete space is very high I would probably suggest the approach outlined above. 

> I checked optimize_acqf_mixed to find that the function ultimately calls optimize_acqf with the given set of possible discrete choices. Is there any performance gain if I use this function instead of manualy using optimize_acqf?

Not really, at least at this point it's largely a convenience wrapper. In the future we hope to implement some heuristics / use our new solver to make it faster. 

cc @dme65

**Comment by sambitmishra98** [comment]
>  evaluate all 2187*7 ~ 15K combinations
Do you mean evaluate the cost function here? The cost function I am using (a numerical simulation) takes about 30 minutes to generate an output. So that's probably not what I would want to do. 

To be a little more precise of what I am doing, I currently use `optimize_acqf` on the [float, int, int, int, int] dataset and rounded off the last 4 to nearest integer. After a few 100 iterations, I find that I have already tried out the suggested rounded candidates. Based on your suggestions, I am thinking that after the suggested candidates repeat too much, I could find the bounds of the best 10 candidates and use `optimize_acqf_mixed`. Is this a reasonable approach?

**Comment by Balandat** [comment]
> Do you mean evaluate the cost function here? The cost function I am using (a numerical simulation) takes about 30 minutes to generate an output. So that's probably not what I would want to do.

No, I mean evaluating the acquisition function. Something like the following

First, make the discrete eval locations
```
import torch
import itertools

X_discrete = torch.tensor(
    list(itertools.product(*[[0, 1, 2] for _ in range(7)], range(1, 8))), # assuming last feature is the float
    dtype=torch.float,
)
```

Batch-evaluate the acquisition function
```
batch_size = 1024  # can probably go higher, might want to watch memory consumption
results = torch.cat(
    [
       acqf(X_batch) for X_batch in torch.split(X_discrete, batch_size)
    ],
    dim=-2,
)
best_X_idcs = torch.topk(results, 40). indices
best_X_discrete = best_X[best_X_idcs, :-1]  
```

Now you have the 40 best acqf values on the grid. You can stick these into a list of dicts, and use `optimize_acqf_mixed`:
```
fixed_features_list = [dict(range(7), Xi) for Xi in best_X_discrete]
optimize_acqf_mixed(acqf, bounds, q=1, fixed_features_list=fixed_features_list)
```

Note that the assumption that `q=1` here is crucial - if you wanted to generate `q` candidates jointly you'd have to look at `2187^q` discrete combinations (unless you use sequential conditioning by using `X_pending` in the acquisition function).

**Comment by sambitmishra98** [comment]
This is gold! Thanks a lot for helping me out with my queries. I will work on everything we discussed here.
