### ISSUE TITLE
[Feature Request] Non-linear constraints on the input space

### ISSUE THREAD

**Issue by K-Kielak** [pytorch/botorch#952]
# 🚀 Feature Request

BoTorch exposes linear constraints API with its `inequality_constraints` and `equality_constraints` arguments to the `optimize_acqf` method and they are extremely useful! However, recently, we have a requirement to support non-linear constraints with the models we're building as well. E.g., constraints such as `x / (y * z) < 500`. 

I know BoTorch uses scipy for optimization under the hood, and scipy already allows for non-linear constraints (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.NonlinearConstraint.html#scipy.optimize.NonlinearConstraint) so it does not seem as a hard feature to implement.

However, I couldn't find any mentions of non-linear constraints in BoTorch. Am I missing something? Is it already somehow available? Or it was simply not implemented yet because other features took a priority?

**Comment by Balandat** [comment]
You're right that nonlinear constraints are currently not supported. But as you said it wouldn't be hard to implement, you'd essentially just pass down the appropriate constraint specification for the scipy optimizer. Of course nonlinear constrained optimization is hard and so solution quality could suffer. However, acquisition function optimization is already non-convex so that's maybe not as big a concern here.

We'd be happy to accept a PR for this :)

**Comment by K-Kielak** [comment]
Thanks for the reply! 

I'll need to implement this feature for my use case sooner or later so I may as well open a PR here then. However, for now, other things took priority, so I'm not sure when exactly will that happen.

**Comment by dme65** [comment]
This was implemented a while ago in #1067. Closing!
